[Distribution]
Distribution=fedora
Release=45
Architecture=arm64

[Output]
Format=directory
Output=mkosi.rootfs
Bootable=no

[Content]
RootPassword=fedora
WithDocs=True
Environment=
    KERNEL_INSTALL_BYPASS=0
Packages=
    NetworkManager
    NetworkManager-adsl
    NetworkManager-ppp
    NetworkManager-tui
    NetworkManager-wifi
    NetworkManager-wwan
    abattis-cantarell-vf-fonts
    acl
    adobe-source-code-pro-fonts
    audit
    avahi
    bash-completion
    binutils
    bluez
    btop
    chrony
    cloud-utils-growpart
    cracklib
    cracklib-dicts
    default-fonts-core-sans
    dhcp-client
    diffutils
    dnf
    dnf-plugins-core
    dnf5-plugins
    dosfstools
    dracut
    e2fsprogs
    efivar
    fastfetch
    findutils
    firefox
    fish
    flatpak
    git
    glib-networking
    glibc-all-langpacks
    google-carlito-fonts
    google-noto-color-emoji-fonts
    google-crosextra-caladea-fonts
    google-droid-sans-fonts
    google-noto-fonts-common
    google-noto-sans-mono-vf-fonts
    google-noto-sans-vf-fonts
    google-noto-serif-vf-fonts
    hostname
    iproute
    iputils
    iptables-nft
    iso-codes
    java-latest-openjdk
    kmod
    langpacks-fonts-en
    liberation-mono-fonts
    liberation-sans-fonts
    liberation-serif-fonts
    librsvg2
    libsane-hpaio
    light
    linux-firmware
    localsearch
    man-db
    man-pages
    mesa-dri-drivers
    mesa-libEGL
    nano
    ncurses
    net-tools
    nodejs-npm
    open-sans-fonts
    openssl
    openssh-clients
    openssh-server
    passwd
    pciutils
    pipa-metapkg
    pipewire
    pipewire-pulseaudio
    plymouth
    plymouth-theme-spinner
    polkit
    rootfiles
    rpm
    rsync
    rygel
    sane-backends-drivers-scanners
    selinux-policy
    sudo
    systemd-oomd-defaults
    systemd-resolved
    systemd-pam
    tar
    tinysparql
    tuned
    tuned-ppd
    unzip
    usbutils
    vim-enhanced
    vim-minimal
    wget
    widevine-installer
    xdg-user-dirs
    wpa_supplicant
    xdg-desktop-portal
    zenity
    zram-generator
    zram-generator-defaults
