[Content]
Packages=
    NetworkManager-openconnect-gnome
    NetworkManager-openvpn-gnome
    NetworkManager-pptp-gnome
    NetworkManager-ssh-gnome
    NetworkManager-vpnc-gnome
    adwaita-mono-fonts
    adwaita-sans-fonts
    eog
    f43-backgrounds-gnome
    gdm
    gnome-backgrounds
    gnome-bluetooth
    gnome-browser-connector
    gnome-calculator
    gnome-clocks
    gnome-color-manager
    gnome-control-center
    gnome-disk-utility
    gnome-epub-thumbnailer
    gnome-extensions-app
    gnome-initial-setup
    gnome-remote-desktop
    gnome-session-wayland-session
    gnome-settings-daemon
    gnome-shell
    gnome-shell-extension-appindicator
    gnome-shell-extension-common
    gnome-shell-extension-screen-autorotate
    gnome-software
    gnome-text-editor
    gnome-tweaks
    gnome-user-share
    gvfs-afc
    gvfs-fuse
    gvfs-goa
    gvfs-gphoto2
    gvfs-mtp
    gvfs-smb
    nautilus
    ptyxis
    seahorse
    sushi
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-user-dirs-gtk
